In [2]:
#formula : yield_of_apple = w1 * temperature + w2 + w3 * humidity

w1, w2, w3 = 0.3, 0.2, 0.5 #value of weight


In [3]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [4]:
kanto_yeild_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yeild_apples

56.8

In [5]:
kanto = [73, 67, 43]
johto= [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [6]:
weights = [w1, w2, w3]

In [7]:
for x, w in zip(kanto, weights):
    print(x)
    print(w)

73
0.3
67
0.2
43
0.5


In [8]:
def crop_yeild(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result    

In [9]:
crop_yeild(kanto, weights)

56.8

In [10]:
!pip install numpy 

Defaulting to user installation because normal site-packages is not writeable


In [11]:
import numpy as np

In [12]:
kanto =  np.array([73, 67, 43])

In [13]:
kanto

array([73, 67, 43])

In [14]:
weights = np.array([0.3, 0.2, 0.5])

In [15]:
type(weights)

numpy.ndarray

In [16]:
weights[0]

np.float64(0.3)

In [17]:
kanto[0]

np.int64(73)

In [18]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).

    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.

    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.

    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.

    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::

        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

    It uses an optimized BLAS library when possible (see `numpy.linalg`).

    Parameters
    ----------
    a : array_like
        Fir

In [19]:
np.dot(kanto, weights)

np.float64(56.8)

In [20]:
kanto

array([73, 67, 43])

In [21]:
weights

array([0.3, 0.2, 0.5])

In [22]:
kanto * weights

array([21.9, 13.4, 21.5])

In [23]:
(kanto * weights).sum()

np.float64(56.8)

In [24]:
#python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

#numpy lists
arr_1 = np.array(arr1)
arr_2 = np.array(arr2)

In [25]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result    

CPU times: total: 203 ms
Wall time: 202 ms


833332333333500000

In [26]:
%%time
np.dot(arr_1, arr_2)

CPU times: total: 0 ns
Wall time: 1.49 ms


np.int64(833332333333500000)

In [27]:
climate_data = np.array([[73, 67, 43],
                        [91, 88, 64],
                        [87, 134, 58],
                        [102, 43, 37],
                        [69, 96, 70]
                        ])

In [28]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [29]:
climate_data.shape

(5, 3)

In [30]:
weights

array([0.3, 0.2, 0.5])

In [31]:
weights.shape

(3,)

In [32]:
arr3 = np.array([
    [[11, 12, 13],
    [13, 14, 15]],

    [[15, 16, 17],
    [17, 18, 19]]
])

In [33]:
arr3.shape

(2, 2, 3)

In [34]:
weights.dtype

dtype('float64')

In [35]:
climate_data.dtype

dtype('int64')

In [36]:
arr3.dtype

dtype('int64')

In [37]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [38]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [39]:
climate_data @ weights #another way to matrix multipication

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [40]:
#importing url
#import urllib.request

In [41]:
#Mathematics: np.sum, np.exp, np.round, arthemtic operators
#array manupulation: np.reshape, np.stack, np.concatenate, np.split
#linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
#statistcc: np.mean , np.median, np.std, np.max

In [42]:
arr4 = np.array([[1, 2, 3, 4],
                [5, 6, 4, 8],
                [9, 1, 2, 3]])

In [43]:
arr5 = np.array([[11,12,13,14],
                [15,16,17,18,],
                [19,11,12,13]])

In [44]:
arr4 + arr5

array([[12, 14, 16, 18],
       [20, 22, 21, 26],
       [28, 12, 14, 16]])

In [45]:
#adding by scalar
arr4 + 3 # add 3 elements of the arr4

array([[ 4,  5,  6,  7],
       [ 8,  9,  7, 11],
       [12,  4,  5,  6]])

In [46]:
arr6 = np.array([4,5,6,7])

In [47]:
arr4 + arr6

array([[ 5,  7,  9, 11],
       [ 9, 11, 10, 15],
       [13,  6,  8, 10]])

In [49]:
#we can use comparison operation in array 
arr7 = np.array([[1,2,3], [3,4,5]])
arr8 = np.array([[2,2,3], [1,2,3]])

In [50]:
arr7 == arr8 

array([[False,  True,  True],
       [False, False, False]])

In [51]:
arr7 != arr8

array([[ True, False, False],
       [ True,  True,  True]])

In [52]:
arr7 >= arr8

array([[False,  True,  True],
       [ True,  True,  True]])

In [53]:
(arr7  == arr8).sum()

np.int64(2)

In [54]:
# array indexing and slicing
arr11 = np.array([
    [[11, 12, 13, 14],
    [13, 14, 15, 19]],

    [[15, 16, 17, 21],
    [63, 92, 36, 18]],

    [[98, 32, 81, 23],
    [17, 18, 19.5, 43]]])

In [55]:
arr11.shape

(3, 2, 4)

In [56]:
arr11[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [57]:
arr11[1, 1]

array([63., 92., 36., 18.])

In [58]:
#single element
arr11[1, 1, 2]

np.float64(36.0)

In [59]:
#subarray using ranges
arr11[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [60]:
arr11[0:, 0:0, 0:1]

array([], shape=(3, 0, 1), dtype=float64)

In [62]:
arr11[0:, 0:1, 0:2]

array([[[11., 12.]],

       [[15., 16.]],

       [[98., 32.]]])

In [63]:
#mixing indices and range
arr11[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [65]:
#using fewer indices
arr11[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [66]:
#other way of creating numpy array
#null 
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [69]:
#all ones
np.ones((3, 3))
np.ones([2, 3, 3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [70]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
#random vector
np.random.rand(3)

array([0.6583032 , 0.04791936, 0.67726204])

In [73]:
#random maxtix
np.random.randn(2, 3)

array([[ 0.43779833,  0.1109055 ,  0.72338475],
       [-0.1856998 , -0.59368215, -0.23172482]])

In [74]:
#fixed value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [75]:
#range with start, end and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [77]:
#3d array
np.arange(10, 90, 3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [78]:
np.arange(10, 90, 3).reshape(3,3,-1)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [76]:
#equall spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [79]:
np.linspace(3, 27, 18)

array([ 3.        ,  4.41176471,  5.82352941,  7.23529412,  8.64705882,
       10.05882353, 11.47058824, 12.88235294, 14.29411765, 15.70588235,
       17.11764706, 18.52941176, 19.94117647, 21.35294118, 22.76470588,
       24.17647059, 25.58823529, 27.        ])